name: GoReleaser

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Extract Go version
        id: go-version
        run: echo "version=$(grep 'go = ' mise.toml | cut -d '"' -f 2)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ steps.go-version.outputs.version }}
          cache: true

      - name: Run GoReleaser build check (Pull Request)
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: v2
          args: build --snapshot --clean

      # GitHub App から一時的なトークンを生成
      - name: Generate Token
        if: startsWith(github.ref, 'refs/tags/')
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          # 自分のリポジトリと Tap リポジトリの両方に権限を絞る（任意）
          owner: ${{ github.repository_owner }}
          repositories: |
            yabumi
            homebrew-tap

      - name: Run GoReleaser release (Tag Push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
